---
- name: Pipeline Down
  hosts: localhost
  tasks:
    - name: Destroying containers
      ansible.builtin.command: >-
        docker compose -f ../docker-compose.yml down --remove-orphans --volumes
      changed_when: false
